source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LabelBlinking_Example', :exclusive => true do
  pod 'LabelBlinking', :path => '../'
end

target 'LabelBlinking_Tests', :exclusive => true do
  pod 'LabelBlinking', :path => '../'

  
end
